import type {
  Container,
  ImageRecord,
  LogLine,
  SessionInfo,
  VolumeRecord,
} from "./types";

const now = Date.now();
const hour = 60 * 60 * 1000;

function logs(lines: Array<[number, LogLine["stream"], string]>): LogLine[] {
  return lines.map(([ago, stream, text]) => ({
    ts: now - ago,
    stream,
    text,
  }));
}

export const seedSession: SessionInfo = {
  name: "Quay",
  dataPath: "C:\\WslcData",
  cpuCount: 4,
  memoryMB: 4096,
  running: true,
  filesystem: "virtiofs",
  networking: "consomme",
  gpu: true,
  gpuName: "NVIDIA GeForce RTX 4080",
  version: "wslc 2.9.3",
  wslVersion: "2.9.3.0",
  missingComponents: [],
  startedAt: now - 3 * hour,
};

export const seedImages: ImageRecord[] = [
  {
    id: "sha256:7d3ef2c1a9b4",
    repository: "nginx",
    tag: "latest",
    digest: "sha256:7d3ef2c1a9b4e81c",
    sizeMB: 187,
    createdAt: now - 12 * hour,
    containers: 1,
  },
  {
    id: "sha256:c4b91e0d22aa",
    repository: "postgres",
    tag: "16",
    digest: "sha256:c4b91e0d22aa91f0",
    sizeMB: 431,
    createdAt: now - 20 * hour,
    containers: 1,
  },
  {
    id: "sha256:9a18f4b0cc71",
    repository: "redis",
    tag: "7",
    digest: "sha256:9a18f4b0cc710012",
    sizeMB: 41,
    createdAt: now - 8 * hour,
    containers: 1,
  },
  {
    id: "sha256:0e55ab8812df",
    repository: "ubuntu",
    tag: "24.04",
    digest: "sha256:0e55ab8812df3341",
    sizeMB: 78.1,
    createdAt: now - 48 * hour,
    containers: 0,
  },
  {
    id: "sha256:f1c0deada11e",
    repository: "alpine",
    tag: "latest",
    digest: "sha256:f1c0deada11e9001",
    sizeMB: 7.8,
    createdAt: now - 6 * hour,
    containers: 1,
  },
  {
    id: "sha256:b77c90e41233",
    repository: "pytorch/pytorch",
    tag: "2.5.1-cuda12.4-cudnn9-runtime",
    digest: "sha256:b77c90e41233aabb",
    sizeMB: 6230,
    createdAt: now - 30 * hour,
    containers: 1,
  },
  {
    id: "sha256:11a0cde4bb90",
    repository: "lscr.io/linuxserver/webtop",
    tag: "ubuntu-kde",
    digest: "sha256:11a0cde4bb90cc21",
    sizeMB: 2480,
    createdAt: now - 15 * hour,
    containers: 1,
  },
];

export const seedVolumes: VolumeRecord[] = [
  {
    name: "pgdata",
    driver: "wslc",
    mountpoint: "/var/lib/wslc/volumes/pgdata",
    sizeMB: 186,
    createdAt: now - 20 * hour,
    inUse: true,
  },
  {
    name: "redisdata",
    driver: "wslc",
    mountpoint: "/var/lib/wslc/volumes/redisdata",
    sizeMB: 12,
    createdAt: now - 8 * hour,
    inUse: true,
  },
  {
    name: "checkpoints",
    driver: "wslc",
    mountpoint: "/var/lib/wslc/volumes/checkpoints",
    sizeMB: 940,
    createdAt: now - 30 * hour,
    inUse: true,
  },
];

export const seedContainers: Container[] = [
  {
    id: "a3f19c8d2e71",
    name: "web",
    image: "nginx:latest",
    status: "running",
    createdAt: now - 2.4 * hour,
    startedAt: now - 2.4 * hour,
    ports: [{ host: 8080, container: 80, protocol: "tcp" }],
    mounts: [],
    env: { NGINX_HOST: "localhost", NGINX_PORT: "80" },
    gpu: false,
    cpuPercent: 2.1,
    memoryMB: 18,
    memoryLimitMB: 512,
    command: ["nginx", "-g", "daemon off;"],
    workdir: "/",
    user: "root",
    logs: logs([
      [2.4 * hour, "stdout", "nginx/1.27.1"],
      [2.3 * hour, "stdout", "start worker processes"],
      [12 * 60 * 1000, "stdout", '172.17.0.1 - GET / HTTP/1.1" 200'],
      [4 * 60 * 1000, "stdout", '172.17.0.1 - GET /favicon.ico HTTP/1.1" 404'],
    ]),
  },
  {
    id: "b91e04aa17c0",
    name: "db",
    image: "postgres:16",
    status: "running",
    createdAt: now - 2.2 * hour,
    startedAt: now - 2.2 * hour,
    ports: [{ host: 5432, container: 5432, protocol: "tcp" }],
    mounts: [
      { source: "pgdata", destination: "/var/lib/postgresql/data", mode: "rw" },
    ],
    env: {
      POSTGRES_USER: "quay",
      POSTGRES_DB: "app",
      POSTGRES_PASSWORD: "••••••",
    },
    gpu: false,
    cpuPercent: 6.4,
    memoryMB: 94,
    memoryLimitMB: 1024,
    command: ["postgres"],
    workdir: "/var/lib/postgresql/data",
    user: "postgres",
    logs: logs([
      [2.2 * hour, "stdout", "database system is ready to accept connections"],
      [40 * 60 * 1000, "stdout", "checkpoint starting: time"],
      [39 * 60 * 1000, "stdout", "checkpoint complete: wrote 42 buffers"],
    ]),
  },
  {
    id: "c0de7781ab45",
    name: "cache",
    image: "redis:7",
    status: "running",
    createdAt: now - 2.1 * hour,
    startedAt: now - 2.1 * hour,
    ports: [{ host: 6379, container: 6379, protocol: "tcp" }],
    mounts: [
      { source: "redisdata", destination: "/data", mode: "rw" },
    ],
    env: {},
    gpu: false,
    cpuPercent: 1.2,
    memoryMB: 8,
    memoryLimitMB: 256,
    command: ["redis-server"],
    workdir: "/data",
    user: "redis",
    logs: logs([
      [2.1 * hour, "stdout", "Ready to accept connections tcp"],
      [15 * 60 * 1000, "stdout", "DB saved on disk"],
    ]),
  },
  {
    id: "d4a12f90ce33",
    name: "webtop",
    image: "lscr.io/linuxserver/webtop:ubuntu-kde",
    status: "running",
    createdAt: now - 1.6 * hour,
    startedAt: now - 1.6 * hour,
    ports: [
      { host: 3000, container: 3000, protocol: "tcp" },
      { host: 3001, container: 3001, protocol: "tcp" },
    ],
    mounts: [
      {
        source: "C:\\Users\\dev\\Desktop",
        destination: "/config",
        mode: "rw",
      },
    ],
    env: { PUID: "1000", PGID: "1000", TZ: "Etc/UTC" },
    gpu: true,
    cpuPercent: 14.8,
    memoryMB: 612,
    memoryLimitMB: 2048,
    command: ["/init"],
    workdir: "/config",
    user: "abc",
    logs: logs([
      [1.6 * hour, "stdout", "KDE Plasma session started"],
      [1.5 * hour, "stdout", "selkies: listening on :3000"],
    ]),
  },
  {
    id: "e87b23c19f60",
    name: "trainer",
    image: "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime",
    status: "running",
    createdAt: now - 52 * 60 * 1000,
    startedAt: now - 52 * 60 * 1000,
    ports: [],
    mounts: [
      {
        source: "checkpoints",
        destination: "/workspace/checkpoints",
        mode: "rw",
      },
      {
        source: "C:\\Users\\dev\\ml",
        destination: "/workspace/src",
        mode: "ro",
      },
    ],
    env: { NVIDIA_VISIBLE_DEVICES: "all" },
    gpu: true,
    cpuPercent: 41.3,
    memoryMB: 1840,
    memoryLimitMB: 4096,
    command: ["python", "train.py"],
    workdir: "/workspace/src",
    user: "root",
    logs: logs([
      [52 * 60 * 1000, "stdout", "torch.cuda.is_available() = True"],
      [51 * 60 * 1000, "stdout", "device: NVIDIA GeForce RTX 4080"],
      [20 * 60 * 1000, "stdout", "epoch 4/20  loss=0.214"],
      [4 * 60 * 1000, "stdout", "epoch 5/20  loss=0.191"],
    ]),
  },
  {
    id: "f01aa9b4d812",
    name: "hello",
    image: "alpine:latest",
    status: "exited",
    createdAt: now - 3.1 * hour,
    startedAt: now - 3.1 * hour,
    finishedAt: now - 3.1 * hour + 1200,
    ports: [],
    mounts: [],
    env: {},
    gpu: false,
    cpuPercent: 0,
    memoryMB: 0,
    memoryLimitMB: 128,
    command: ["echo", "Hello from WSL container!"],
    workdir: "/",
    user: "root",
    exitCode: 0,
    logs: logs([
      [3.1 * hour, "stdout", "Hello from WSL container!"],
    ]),
  },
];

export const catalogImages = [
  "nginx:latest",
  "postgres:16",
  "redis:7",
  "ubuntu:24.04",
  "alpine:latest",
  "python:3.12",
  "node:22",
  "golang:1.23",
  "httpd:2.4",
  "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime",
  "lscr.io/linuxserver/webtop:ubuntu-kde",
];
