name: Create RC tag

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  tag:
    if: github.event.head_commit.message == 'Create temporary RC tag workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create v0.1.4-rc1
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a v0.1.4-rc1 -m "Quay v0.1.4-rc1"
          git push origin v0.1.4-rc1
